### PR TITLE
fix  #155 : Calculation fails when global aesthetic values contain something not supported by geom

### LINKED ISSUE #155: Calculation fails when global aesthetic values contain something not supported by geom
See example below.
It works if removing `shape = legend` from `aes()` or `gghighlight::gghighlight(legend == 'a')` from layers.

## reprex

``` r
library(dplyr, warn.conflicts = FALSE)
library(ggplot2)
data.frame(
    X = c(1, 2, 1, 2),
    Y = c(1, 1, 2, 2),
    legend = c('a', 'a', 'b', 'b')
) %>%
    ggplot() +
    aes(X, Y, color = legend, shape = legend) +
    geom_line() +
    gghighlight::gghighlight(legend == 'a')
#> Warning: Tried to calculate with group_by(), but the calculation failed.
#> Falling back to ungrouped filter operation...
#> label_key: legend
#> Don't know how to automatically pick scale for object of type function. Defaulting to continuous.
#> Error: A continuous variable can not be mapped to shape
```

<sup>Created on 2020-07-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### PR DESCRIPTION
**Pull request by atusy**

### CODE REVIEW

**Comment by yutannihilation** [comment]
Why do you think this `if` branch can be removed? This doesn't feel the right direction to me...

**Comment by atusy** [comment]
I just found solution by some trial and errors, and am not confident about the direction...

Anyway, I describe the way I come up with this PR.

In the reprex in #155, I see following message.

> Don't know how to automatically pick scale for object of type function. Defaulting to continuous.

I guessed this is caused by a `legend` column, as `legend` is a function exported by the `graphics` package.
Thus, I renamed the `legend` column to the `Z` column, and found

> #> Error in FUN(X[[i]], ...): object 'Z' not found

Then, I come up with an idea to `bind_cols` the original data.

``` r
library(dplyr, warn.conflicts = FALSE)
library(ggplot2)
data.frame(
  X = c(1, 2, 1, 2),
  Y = c(1, 1, 2, 2),
  Z = c('a', 'a', 'b', 'b')
) %>%
  ggplot() +
  aes(X, Y, color = Z, shape = Z) +
  geom_line() +
  gghighlight::gghighlight(Z == 'a')
#> Warning: Tried to calculate with group_by(), but the calculation failed.
#> Falling back to ungrouped filter operation...
#> label_key: Z
#> Error in FUN(X[[i]], ...): object 'Z' not found
```

<sup>Created on 2020-07-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by yutannihilation** [comment]
A quick hint; this PR is breaking this usage (sorry, I don't have time to explain (or remember :roll_eyes:) the detail for now...)

``` r
library(gghighlight)
#> Loading required package: ggplot2

ggplot(mpg, aes(displ, hwy, colour = class)) +
  geom_point() +
  facet_wrap(vars(class)) +
  gghighlight(use_direct_label = FALSE)
```



<sup>Created on 2020-07-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by atusy** [comment]
Oh thanks! This if branch is not just for efficiency......


I close this PR, and hope myself be back with a new solution.

**Comment by yutannihilation** [comment]
Btw, this PR means `calculate_per_facet = TRUE` is a workaround for your original issue.

``` r
library(dplyr, warn.conflicts = FALSE)
library(ggplot2)
data.frame(
  X = c(1, 2, 1, 2),
  Y = c(1, 1, 2, 2),
  Z = c('a', 'a', 'b', 'b')
) %>%
  ggplot() +
  aes(X, Y, color = Z, shape = Z) +
  geom_line() +
  gghighlight::gghighlight(Z == 'a', calculate_per_facet = TRUE)
#> Warning: Tried to calculate with group_by(), but the calculation failed.
#> Falling back to ungrouped filter operation...
#> label_key: Z
```



<sup>Created on 2020-07-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Pull request closed without merging**
